// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/30/2026, 12:32:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/biji/Projects/bookstore/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/plugins/**/*.{js,ts,mjs}","/home/biji/Projects/bookstore/frontend/composables/**/*.{js,ts,mjs}","/home/biji/Projects/bookstore/frontend/utils/**/*.{js,ts,mjs}","/home/biji/Projects/bookstore/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/biji/Projects/bookstore/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;